import type { NextPage } from 'next'
import Head from 'next/head'
import Ads from '../Components/Ads'
import Header from '../Components/Header'
import Banner from '../Components/Banner'
import Menu from '../Components/Menu'
import FlashSale from '../Components/FlashSale'
import Collections from '../Components/Collections'
import LazMall from '../Components/LazMall'
import Categories from '../Components/Categories'
import JustForYou from '../Components/JustForYou'
import Promotion from '../Components/Promotion'
import Payment from '../Components/Payment'
import Magazine from '../Components/Magazine'
import Footer from '../Components/Footer'

const Home: NextPage = () => {
  return (
    <div className={`container`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Ads/>
      </header>
      
      <main className={`main`}>
      <Header/>
          <Banner/>
          <div className={`padding`}>
          <Menu/>
          <FlashSale/>
          <Collections/>
          <LazMall/>
          <Categories/>
          <JustForYou/>
          <Promotion/>
          </div>
          <Payment/>
          <div className={`padding`}>
          <Magazine/> 
          </div>
      </main>

      <footer className={`footer`}>
        <Footer/>
      </footer>
    </div>
  )
}

export default Home
